project:
  type: website
  output-dir: docs
  resources:
    - "docs/posts/2025-27-06-iata-codes/index.html"
    - "docs/posts/2025-0707-projection-explorer/index.html"
    - "docs/posts/2021-09-23-dulux-colours-map/dulux-colours-map.html"
    - "docs/posts/2021-10-20-random-even-points-on-the-globe/random-even-points-on-the-globe.html"
    - "docs/posts/2021-10-21-experiments-with-R-interpolators/experiments-with-R-interpolators.html"
    - "docs/posts/2021-10-21-kde/kde.html"
    - "docs/posts/2021-10-22-spatstat-idw/spatstat-idw.html"
    - "docs/posts/2021-10-30-locations-of-interest/locations-of-interest.html"
    - "docs/posts/2021-12-08-affine-transformation-of-sf-objects/affine-transformation-of-sf-objects.html"
    - "docs/posts/2021-12-08-low-level-handling-sf-objects/low-level-sf-objects.html"
    - "CNAME"

website:
  title: "Geospatial Stuff"
  site-url: https://geospatialstuff.com
  open-graph: true
  description: "All manner of geospatial stuff"  
  navbar:
    logo: /images/gs-logo-corrected.png
    right:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "Contact"
        file: contact.qmd
      - text: "Training"
        file: training.qmd
      - text: "More"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publications"
            file: publications.qmd
          - text: "Computing Geographically"
            href: https://geospatialstuff.com/computing-geographically
            target: _blank
            icon: box-arrow-up-right
          - text: "Spatial Simulation"
            href: https://geospatialstuff.com/pattern-and-process
            target: _blank
            icon: box-arrow-up-right
          # trailing nbsps to give external link icon room to float right
          - text: "30 Day Map Challenge 2023\xa0\xa0\xa0\xa0\xa0\u202f"
            href: https://geospatialstuff.com/30-day-maps-2023
            target: _blank
            icon: box-arrow-up-right
      - icon: linkedin
        href: https://www.linkedin.com/in/david-o-sullivan-1b8a901b7/
      - icon: rss
        href: blog.xml
  favicon: /images/gs-logo-corrected.png
  draft-mode: unlinked
  body-footer: |
    <a href="/"><img src="/images/gs-logo-corrected.png" style="height:36px;" alt="Geospatial Stuff"></a>

format:
  html:
    theme: lux
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:\/\/|https:\/\/)(?:dosull\.github\.io|geospatialstuff\.com|southosullivan\.com|github\.com\/DOSull|southosullivan\.com|patternandprocess\.org|computinggeographically\.org)'
    highlight-style: ayu
    include-in-header:
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="06075b90-0666-47f4-af54-6e7b8f59e570" data-domains="geospatialstuff.com,dosull.github.io"></script>
          <meta name="keywords" content="geospatial, R, python, simulation, cartography, visualization, spatial analysis, complexity, training">
