project:
  type: website
  output-dir: docs
  # resources to redirect from mistaken folder names and old folder structure
  resources:
    - "docs/posts/2020-07-18-what-the-chord/what-3-chords.html"
    - "docs/posts/2021-09-23-dulux-colours-map/dulux-colours-map.html"
    - "docs/posts/2021-10-20-random-even-points-on-the-globe/random-even-points-on-the-globe.html"
    - "docs/posts/2021-10-21-experiments-with-R-interpolators/experiments-with-R-interpolators.html"
    - "docs/posts/2021-10-21-kde/kde.html"
    - "docs/posts/2021-10-22-spatstat-idw/spatstat-idw.html"
    - "docs/posts/2021-10-30-locations-of-interest/locations-of-interest.html"
    - "docs/posts/2021-12-08-affine-transformation-of-sf-objects/affine-transformation-of-sf-objects.html"
    - "docs/posts/2021-12-08-low-level-handling-sf-objects/low-level-sf-objects.html"
    - "docs/posts/2022-03-09-ok-covid-you-win/ok-covid-you-win.html"
    - "docs/posts/2022-08-03-spiral-folds/spiral-folds.html"
    - "docs/posts/2024-08-02-model-zoo-latest/model-zoo.html"
    - "docs/posts/2024-08-15-netlogo-utils/netlogo-utils.html"
    - "docs/posts/2024-08-30-geocart-24/geocart-24.html"
    - "docs/posts/2024-10-10-giscience-2025/giscience-2025.html"
    - "docs/posts/2024-10-16-geopackages/in-praise-of-the-geopackage.html"
    - "docs/posts/2024-10-17-duckdb/duckdb.html"
    - "docs/posts/2024-11-16-tmap-vs-ggplot/tmap4-vs-ggplot2.html"
    - "docs/posts/2024-11-22-algim-2024/algim-2024.html"
    - "docs/posts/2024-11-27-systems-thinking/systems-thinking.html"
    - "docs/posts/2025-01-13-random-points-on-globe-revisited/random-points-on-globe.html"
    - "docs/posts/2025-01-28-waiopehu/waiopehu-tramp.html"
    - "docs/posts/2025-03-09-mapweaver-beta/mapweaver-beta.html"
    - "docs/posts/2025-04-30-setting-up-a-jupyter-hub/jupyter-hub.html"
    - "docs/posts/2025-05-02-tiles-and-glyphs/tiles-and-glyphs.html"
    - "docs/posts/2025-05-16-xkcd-bad-projections-ranked/xkcd-bad-projections-ranked.html"
    - "docs/posts/2025-05-22-python-meetup-talk/python-meetup-talk.html"
    - "docs/posts/2025-06-01-nsew-island/index.html"
    - "docs/posts/2025-06-13-population-quadrants/index.html"
    - "docs/posts/2025-06-20-population-binary-space-partition/index.html"
    - "docs/posts/2025-27-06-iata-codes/index.html"
    - "docs/posts/2025-06-27-iata-codes/index.html"
    - "docs/posts/2025-0707-projection-explorer/index.html"
    - "docs/posts/2025-07-07-projection-explorer/index.html"
    - "docs/posts/2025/07/07/projection-explorer/index.html"
    - "docs/posts/2025-07-10-hulls-tetrahedra/index.html"
    - "docs/posts/2025-07-30-counting-points-in-polygons/index.html"
    - "docs/posts/2025-08-03-dulux-colours-in-python/index.html"
    - "docs/posts/2025-08-13-temperature-dials/index.html"
    - "docs/posts/2025-08-20-street-level-isochrones/index.html"
    - "docs/posts/2025-08-31-gia-chapter-1A/index.html"
    - "docs/posts/2025-09-09-gia-chapter-1B-part-1/index.html"
    - "docs/posts/2025-09-10-reflections-on-giscience-2025/index.html"
    - "docs/posts/2025-09-12-gia-chapter-1B-part-2/index.html"
    - "docs/posts/2025-09-17-gia-chapter-1B-part-3A/index.html"
    - "docs/posts/2025-10-04-barthelemy-boeing-and-co/index.html"
    - "docs/posts/2025-10-05-gia-chapter-1B-part-3B/index.html"
    - "docs/posts/2025-10-14-gia-chapter-1B-part-3C/index.html"
    - "docs/posts/2025-10-23-gia-chapter-1B-part-4/index.html"
    - "docs/posts/2025-10-27-xkcd-3122-interrupted-spheres/index.html"
    - "docs/posts/2025-11-03-gia-chapter-1B-part-4B/index.html"
    - "docs/posts/2025-11-03-hachures-30-day-maps-2025-day-2/index.html"
    - "docs/posts/2025-11-09-origami-terrain-30-day-maps-2025-day-9/index.html"
    - "docs/posts/2025-11-14-gia-chapter-2A-spatial-autocorrelation/index.html"
    - "docs/posts/2025-11-18-tanaka-30-day-maps-2025-day-18/index.html"
    - "docs/posts/2025-11-26-city-to-sea/index.html"
    - "docs/posts/2025-12-20-paparoa-track/index.html"
    - "docs/posts/2026-01-21-bivariate-choropleths/index.html"
    - "docs/posts/2026-01-29-gia-chapter-2B-maup/index.html"
    - "docs/posts/2026-02-02-netlogo/index.html"
    - "CNAME"

website:
  title: "Geospatial Stuff"
  site-url: https://geospatialstuff.com
  open-graph: true
  description: "All manner of geospatial stuff"  
  navbar:
    logo: /images/gs-logo-corrected.png
    right:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Posts"
        file: blog.qmd
      - text: "Contact"
        file: contact.qmd
      - text: "Training"
        file: training.qmd
      - text: "More"
        menu:
          - text: "Books"
            file: books.qmd
          - text: "Presentations"
            file: presentations.qmd
          - text: "Publications"
            file: publications.qmd
          - text: "Computing Geographically"
            href: https://geospatialstuff.com/computing-geographically
            target: _blank
            icon: box-arrow-up-right
          - text: "Spatial Simulation"
            href: https://geospatialstuff.com/pattern-and-process
            target: _blank
            icon: box-arrow-up-right
          # trailing nbsps to give external link icon room to float right
          - text: "30 Day Map Challenge 2023\xa0\xa0\xa0\xa0\xa0\u202f"
            href: https://geospatialstuff.com/30-day-maps-2023
            target: _blank
            icon: box-arrow-up-right
      - icon: linkedin
        href: https://www.linkedin.com/in/david-o-sullivan-1b8a901b7/
      - icon: rss
        href: blog.xml
  favicon: /images/gs-logo-corrected.png
  draft-mode: unlinked
  body-footer: |
    <a href="/"><img src="/images/gs-logo-corrected.png" style="height:36px;" alt="Geospatial Stuff"></a>

format:
  html:
    theme: lux
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:\/\/|https:\/\/)(?:dosull\.github\.io|geospatialstuff\.com|southosullivan\.com|github\.com\/DOSull|southosullivan\.com|patternandprocess\.org|computinggeographically\.org)'
    highlight-style: ayu
    include-in-header:
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="06075b90-0666-47f4-af54-6e7b8f59e570" data-domains="geospatialstuff.com,dosull.github.io"></script>
          <meta name="keywords" content="geospatial, R, python, simulation, cartography, visualization, spatial analysis, complexity, training">

